[AFRM]
MONITOR_PLATFORM=SOLARMAN# 平台名称
MONITOR_SENSOR_SN=3517398083# 平台提供的SN
MONITOR_SENSOR_TYPE=4G# 设备联网类型4G/ETH
MONITOR_SERVER_IP=47.254.74.158# 设备通信服务器
MONITOR_SERVER_PORT=10000# 设备通信服务器端口
MONITOR_DATA_FILE=/mmz/data/monitor.data# 监控数据路径
MODE_4G=PPP# 4G拨号类型
[AFUART]
UART_BAUD_1E0A=9600# 1E0A设备的通信波特率[9600/115200]
UART_BAUD_1E2X=9600# 1E2X设备的通信波特率[9600/115200]
UART_STATION_CAPACITY_1E0A=5500# 1E0A设备的功率
UART_STATION_CAPACITY_1E2X=9900# 1E2X设备的功率
UART_INVERTER_NUM=9#
UART1_INVERTER_NUM=9# RS485串口1的设备连接数量
UART2_INVERTER_NUM=9# RS485串口2的设备连接数量
UART_POWER_SET=1# 1:出力控制 0:仅监控
[AFRC]
CONTROL_SERVER_NAME=re-ene.energia.co.jp#
CONTROL_SERVER_URL=https://re-ene.energia.co.jp/scheduleSend/# 电力公司服务器
CONTROL_SERVER_PORT=443# 端口
CONTROL_ID=07900000000899299999990016# 电站ID
CONTROL_NTP_SERVER=re-ene.energia.co.jp# NTP校时服务器
[4G]
SIM_APN=vmobile.jp# SIM卡运营商APN
SIM_USER=qtnet@bbiq.jp# SIM卡账户
SIM_PASSWORD=bbiq# SIM卡密码
[WIFI]
WIFI_NAME=www.com#
WIFI_PASSWORD=123456#
